import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { AlertTriangle, CheckCircle2, Plus, Waves, X } from "lucide-react";
import type { PoolLogRecord } from "../../../shared/contracts";
import { useAuth } from "../../contexts/AuthContext";
import { useProperty } from "../../contexts/PropertyContext";
import { api } from "../../lib/api";

const readings: Array<[keyof PoolForm, string, string]> = [["freeChlorine", "Free chlorine", "1–4 ppm"], ["totalChlorine", "Total chlorine", "ppm"], ["ph", "pH", "7.2–7.8"], ["alkalinity", "Alkalinity", "80–120 ppm"], ["hardness", "Hardness", "200–400 ppm"], ["cyanuricAcid", "Cyanuric acid", "30–50 ppm"], ["waterTempF", "Water temperature", "°F"]];
type PoolForm = { logDate: string; freeChlorine: string; totalChlorine: string; ph: string; alkalinity: string; hardness: string; cyanuricAcid: string; waterTempF: string; weatherSummary: string; notes: string };

export function PoolLogsTab() {
  const { propertyId } = useProperty(); const { can } = useAuth(); const [open, setOpen] = useState(false);
  const query = useQuery({ queryKey: ["pool-logs", propertyId], queryFn: () => api<{ poolLogs: PoolLogRecord[] }>(`/api/properties/${propertyId}/pool-logs`), enabled: Boolean(propertyId) });
  return <section className="ops-section"><header className="ops-section__header"><div><p className="eyebrow">Amenity compliance</p><h2>Pool logs</h2><p>Record chemistry consistently; out-of-range readings are flagged automatically.</p></div>{can("pool:manage") && <button className="button button--primary" onClick={() => setOpen(true)}><Plus size={16} />Log readings</button>}</header>
    <div className="pool-log-list">{query.data?.poolLogs.map((log) => <article className={`pool-log-card ${log.exceptions.length ? "pool-log-card--exception" : ""}`} key={log.id}><header><span className="pool-log-card__status">{log.exceptions.length ? <AlertTriangle /> : <CheckCircle2 />}</span><div><strong>{formatDate(log.logDate)}</strong><small>{log.createdByName} · {new Date(log.loggedAt).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</small></div><span className={log.exceptions.length ? "exception-pill" : "compliant-pill"}>{log.exceptions.length ? `${log.exceptions.length} exceptions` : "In range"}</span></header><div className="reading-grid"><Reading label="Free chlorine" value={log.freeChlorine} suffix="ppm" /><Reading label="pH" value={log.ph} /><Reading label="Alkalinity" value={log.alkalinity} suffix="ppm" /><Reading label="Temperature" value={log.waterTempF} suffix="°F" /></div>{log.exceptions.length > 0 && <ul className="exception-list">{log.exceptions.map((item) => <li key={item}>{item}</li>)}</ul>}{(log.weatherSummary || log.notes) && <footer>{log.weatherSummary && <span>{log.weatherSummary}</span>}{log.notes && <p>{log.notes}</p>}</footer>}</article>)}</div>
    <PoolLogDialog open={open} onClose={() => setOpen(false)} />
  </section>;
}
function Reading({ label, value, suffix = "" }: { label: string; value: number | null; suffix?: string }) { return <span><small>{label}</small><strong>{value ?? "—"}{value !== null && suffix ? <em> {suffix}</em> : null}</strong></span>; }

function PoolLogDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { propertyId } = useProperty(); const queryClient = useQueryClient(); const empty: PoolForm = { logDate: new Date().toISOString().slice(0, 10), freeChlorine: "", totalChlorine: "", ph: "", alkalinity: "", hardness: "", cyanuricAcid: "", waterTempF: "", weatherSummary: "", notes: "" };
  const [form, setForm] = useState(empty); const [error, setError] = useState("");
  const mutation = useMutation({ mutationFn: () => { const numeric = Object.fromEntries(readings.map(([key]) => [key, form[key] === "" ? null : Number(form[key])])); return api(`/api/properties/${propertyId}/pool-logs`, { method: "POST", body: JSON.stringify({ ...numeric, logDate: form.logDate, weatherSummary: form.weatherSummary || null, notes: form.notes || null }) }); }, onSuccess: async () => { await Promise.all([queryClient.invalidateQueries({ queryKey: ["pool-logs", propertyId] }), queryClient.invalidateQueries({ queryKey: ["operations", propertyId] }), queryClient.invalidateQueries({ queryKey: ["notifications"] })]); onClose(); } });
  if (!open) return null; const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); try { await mutation.mutateAsync(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save readings"); } };
  return <div className="modal-layer"><section className="dialog"><header className="dialog__header"><span className="dialog__icon"><Waves /></span><div><p className="eyebrow">Daily record</p><h2>Log pool readings</h2></div><button className="icon-button" onClick={onClose}><X /></button></header><form onSubmit={submit}><div className="form-grid"><label className="field field--full"><span>Log date</span><input type="date" required value={form.logDate} onChange={(event) => setForm({ ...form, logDate: event.target.value })} /></label>{readings.map(([key, label, hint]) => <label className="field" key={key}><span>{label}<small>{hint}</small></span><input type="number" min="0" step="0.01" value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></label>)}<label className="field"><span>Weather</span><input value={form.weatherSummary} onChange={(event) => setForm({ ...form, weatherSummary: event.target.value })} placeholder="Sunny, 86°F" /></label><label className="field field--full"><span>Notes</span><textarea rows={3} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div>{error && <p className="form-error">{error}</p>}<footer className="dialog__footer"><button type="button" className="button button--ghost" onClick={onClose}>Cancel</button><button className="button button--primary" disabled={mutation.isPending}>Save readings</button></footer></form></section></div>;
}
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { weekday: "short", month: "short", day: "numeric" }).format(new Date(`${value}T12:00:00`));
