import { useMemo, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Building2, Plus, Refrigerator, Search, X } from "lucide-react";
import type { ApplianceRecord, UnitSummary } from "../../shared/contracts";
import { DetailModal } from "../components/DetailModal";
import { EmptyState } from "../components/EmptyState";
import { StatusBadge } from "../components/StatusBadge";
import { useAuth } from "../contexts/AuthContext";
import { useProperty } from "../contexts/PropertyContext";
import { api } from "../lib/api";

export function UnitsPage() {
  const requestedStatus = new URLSearchParams(window.location.search).get("status");
  const { property, propertyId } = useProperty(); const [search, setSearch] = useState(""); const [status, setStatus] = useState(["occupied", "notice", "vacant", "down"].includes(requestedStatus ?? "") ? requestedStatus! : "all"); const [selected, setSelected] = useState<UnitSummary | null>(null);
  const query = useQuery({ queryKey: ["units", propertyId], queryFn: () => api<{ units: UnitSummary[] }>(`/api/properties/${propertyId}/units`), enabled: Boolean(propertyId) });
  const units = useMemo(() => { const term = search.toLowerCase().trim(); return (query.data?.units ?? []).filter((unit) => (status === "all" || unit.occupancyStatus === status) && (!term || `${unit.unitNumber} ${unit.buildingName} ${unit.floorPlanName}`.toLowerCase().includes(term))); }, [query.data, search, status]);
  return <div className="page-stack"><section className="page-heading"><div><p className="eyebrow">{property?.name}</p><h1>Unit directory</h1><p>{query.data?.units.length ?? 0} units with occupancy, make-ready, and asset context.</p></div></section><section className="toolbar"><label className="search-field"><Search size={18} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search unit, building, or floor plan" /></label><div className="segmented-control" aria-label="Filter units by status">{["all", "occupied", "notice", "vacant", "down"].map((value) => <button key={value} className={status === value ? "active" : ""} onClick={() => setStatus(value)}>{value}</button>)}</div></section><section className="panel table-panel">{units.length ? <div className="data-table-wrap"><table className="data-table data-table--interactive"><thead><tr><th>Unit</th><th>Building</th><th>Floor plan</th><th>Details</th><th>Occupancy</th><th>Make ready</th><th /></tr></thead><tbody>{units.map((unit) => <tr key={unit.id} onClick={() => setSelected(unit)}><td><span className="unit-number">{unit.unitNumber}</span></td><td>{unit.buildingName}</td><td><strong>{unit.floorPlanName}</strong></td><td className="muted">{unit.bedrooms} bd · {unit.bathrooms} ba · {unit.squareFeet.toLocaleString()} ft²</td><td><span className={`occupancy occupancy--${unit.occupancyStatus}`}>{unit.occupancyStatus}</span></td><td>{unit.activeTurnStatus ? <StatusBadge status={unit.activeTurnStatus} /> : <span className="muted">—</span>}</td><td><button className="text-button">View assets</button></td></tr>)}</tbody></table></div> : <EmptyState icon={Building2} title="No units found" detail="Try clearing your search or selecting a different status." />}</section><UnitAssetsModal unit={selected} onClose={() => setSelected(null)} /></div>;
}

function UnitAssetsModal({ unit, onClose }: { unit: UnitSummary | null; onClose: () => void }) {
  const { can } = useAuth(); const [adding, setAdding] = useState(false);
  const query = useQuery({ queryKey: ["appliances", unit?.id], queryFn: () => api<{ appliances: ApplianceRecord[] }>(`/api/units/${unit?.id}/appliances`), enabled: Boolean(unit) });
  if (!unit) return null;
  return <DetailModal eyebrow="Unit assets" title={`Unit ${unit.unitNumber}`} icon={Building2} labelledBy="unit-assets-title" onClose={adding ? () => setAdding(false) : onClose} className="unit-detail-modal"><section className="unit-asset-hero"><span className="unit-number">{unit.unitNumber}</span><div><h3>{unit.floorPlanName}</h3><p>{unit.buildingName} · {unit.bedrooms} bd · {unit.bathrooms} ba · {unit.squareFeet.toLocaleString()} ft²</p></div><span className={`occupancy occupancy--${unit.occupancyStatus}`}>{unit.occupancyStatus}</span></section><section className="appliance-section"><header><div><p className="eyebrow">Installed equipment</p><h3>Appliances</h3></div>{can("units:update") && <button className="button button--primary button--small" onClick={() => setAdding(true)}><Plus size={14} />Add appliance</button>}</header><div className="appliance-list">{query.data?.appliances.map((item) => <article key={item.id}><span><Refrigerator /></span><div><strong>{item.type}</strong><p>{[item.brand, item.model].filter(Boolean).join(" · ") || "Details not recorded"}</p><small>Serial: {item.serialNumber ?? "—"}{item.warrantyExpiry ? ` · Warranty to ${formatDate(item.warrantyExpiry)}` : ""}</small></div></article>)}{!query.data?.appliances.length && <p className="attachment-empty"><Refrigerator size={16} />No appliances recorded</p>}</div></section><ApplianceDialog unitId={unit.id} open={adding} onClose={() => setAdding(false)} /></DetailModal>;
}

function ApplianceDialog({ unitId, open, onClose }: { unitId: string; open: boolean; onClose: () => void }) {
  const queryClient = useQueryClient(); const [form, setForm] = useState({ type: "", brand: "", model: "", serialNumber: "", installDate: "", warrantyExpiry: "", notes: "" }); const [error, setError] = useState("");
  const mutation = useMutation({ mutationFn: () => api(`/api/units/${unitId}/appliances`, { method: "POST", body: JSON.stringify(Object.fromEntries(Object.entries(form).map(([key, value]) => [key, value || null]))) }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["appliances", unitId] }); onClose(); } });
  if (!open) return null; const submit = async (event: FormEvent) => { event.preventDefault(); setError(""); try { await mutation.mutateAsync(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not add appliance"); } };
  return <div className="modal-layer"><section className="dialog"><header className="dialog__header"><span className="dialog__icon"><Refrigerator /></span><div><p className="eyebrow">Asset record</p><h2>Add appliance</h2></div><button className="icon-button" onClick={onClose}><X /></button></header><form onSubmit={submit}><div className="form-grid"><label className="field"><span>Type</span><input required minLength={2} value={form.type} onChange={(event) => setForm({ ...form, type: event.target.value })} placeholder="Refrigerator" /></label><label className="field"><span>Brand</span><input value={form.brand} onChange={(event) => setForm({ ...form, brand: event.target.value })} /></label><label className="field"><span>Model</span><input value={form.model} onChange={(event) => setForm({ ...form, model: event.target.value })} /></label><label className="field"><span>Serial number</span><input value={form.serialNumber} onChange={(event) => setForm({ ...form, serialNumber: event.target.value })} /></label><label className="field"><span>Install date</span><input type="date" value={form.installDate} onChange={(event) => setForm({ ...form, installDate: event.target.value })} /></label><label className="field"><span>Warranty expiry</span><input type="date" value={form.warrantyExpiry} onChange={(event) => setForm({ ...form, warrantyExpiry: event.target.value })} /></label><label className="field field--full"><span>Notes</span><textarea rows={3} value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></label></div>{error && <p className="form-error">{error}</p>}<footer className="dialog__footer"><button type="button" className="button button--ghost" onClick={onClose}>Cancel</button><button className="button button--primary">Add appliance</button></footer></form></section></div>;
}
const formatDate = (value: string) => new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(`${value}T12:00:00`));
