/**
 * Punch List Template Generator
 * Generates appropriate punch list items based on apartment bed/bath configuration
 */

export interface PunchListItemData {
  label: string;
  area: string;
  category: string;
}

const punchListTemplates: Record<string, PunchListItemData[]> = {
  '1-1': [ // 1 Bed 1 Bath
    // Master Bedroom
    { label: 'Ceiling fan', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Outlets', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Wall switch plate', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Closet globe', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Blinds', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Window screen', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Entry door', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Door stop', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Master Bedroom', category: 'HVAC/Ventilation' },
    { label: 'Paint', area: 'Master Bedroom', category: 'Paint/Finishes' },
    { label: 'Carpet', area: 'Master Bedroom', category: 'Flooring' },
    // Master Bathroom
    { label: 'Light bulbs', area: 'Master Bathroom', category: 'Electrical' },
    { label: 'Switch cover', area: 'Master Bathroom', category: 'Electrical' },
    { label: 'Exhaust fan', area: 'Master Bathroom', category: 'Electrical' },
    { label: 'Toilet', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Toilet seat', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Sink', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Shower head', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Tub', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Tub drain', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Diverter', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Faucet', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Cabinets', area: 'Master Bathroom', category: 'Cabinetry' },
    { label: 'TP roll holder', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Towel bar', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Shower rod', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door stop', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door', area: 'Master Bathroom', category: 'Doors & Windows' },
    { label: 'Closet door', area: 'Master Bathroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Master Bathroom', category: 'HVAC/Ventilation' },
    { label: 'Countertops', area: 'Master Bathroom', category: 'Paint/Finishes' },
    { label: 'Tub surround', area: 'Master Bathroom', category: 'Paint/Finishes' },
    { label: 'Closet shelves', area: 'Master Bathroom', category: 'Paint/Finishes' },
    // Kitchen
    { label: 'Range', area: 'Kitchen', category: 'Appliances' },
    { label: 'Refrigerator', area: 'Kitchen', category: 'Appliances' },
    { label: 'Dishwasher', area: 'Kitchen', category: 'Appliances' },
    { label: 'Sink', area: 'Kitchen', category: 'Plumbing' },
    { label: 'Faucet', area: 'Kitchen', category: 'Plumbing' },
    { label: 'Cabinet doors', area: 'Kitchen', category: 'Cabinetry' },
    { label: 'Countertops', area: 'Kitchen', category: 'Paint/Finishes' },
    { label: 'Paint', area: 'Kitchen', category: 'Paint/Finishes' },
    { label: 'Tile backsplash', area: 'Kitchen', category: 'Paint/Finishes' },
    { label: 'Light fixtures', area: 'Kitchen', category: 'Electrical' },
    { label: 'Outlets', area: 'Kitchen', category: 'Electrical' },
    { label: 'Register', area: 'Kitchen', category: 'HVAC/Ventilation' },
    // Living/Dining
    { label: 'Ceiling fan', area: 'Living/Dining Room', category: 'Electrical' },
    { label: 'Light fixtures', area: 'Living/Dining Room', category: 'Electrical' },
    { label: 'Outlets', area: 'Living/Dining Room', category: 'Electrical' },
    { label: 'Window blinds', area: 'Living/Dining Room', category: 'Doors & Windows' },
    { label: 'Window screens', area: 'Living/Dining Room', category: 'Doors & Windows' },
    { label: 'Sliding glass door', area: 'Living/Dining Room', category: 'Doors & Windows' },
    { label: 'Paint', area: 'Living/Dining Room', category: 'Paint/Finishes' },
    { label: 'Flooring', area: 'Living/Dining Room', category: 'Flooring' },
    { label: 'Register', area: 'Living/Dining Room', category: 'HVAC/Ventilation' },
    // Entry/Hallway
    { label: 'Light fixture', area: 'Entry/Hallway', category: 'Electrical' },
    { label: 'Outlets', area: 'Entry/Hallway', category: 'Electrical' },
    { label: 'Entry door', area: 'Entry/Hallway', category: 'Doors & Windows' },
    { label: 'Door frame', area: 'Entry/Hallway', category: 'Doors & Windows' },
    { label: 'Paint', area: 'Entry/Hallway', category: 'Paint/Finishes' },
    { label: 'Flooring', area: 'Entry/Hallway', category: 'Flooring' },
    // Laundry
    { label: 'Washer/Dryer hookup', area: 'Laundry', category: 'Plumbing' },
    { label: 'Vent to exterior', area: 'Laundry', category: 'HVAC/Ventilation' },
    // A/C Closet
    { label: 'Filter', area: 'A/C Closet', category: 'HVAC/Ventilation' },
    { label: 'Heat', area: 'A/C Closet', category: 'HVAC/Ventilation' },
    { label: 'A/C', area: 'A/C Closet', category: 'HVAC/Ventilation' },
    { label: 'Water heater', area: 'A/C Closet', category: 'Plumbing' },
    { label: 'Condensate lines', area: 'A/C Closet', category: 'Plumbing' },
    { label: 'Drip pan', area: 'A/C Closet', category: 'Plumbing' },
    // Patio
    { label: 'Globe', area: 'Patio', category: 'Electrical' },
    { label: 'Closet door', area: 'Patio', category: 'Doors & Storage' },
    { label: 'Decking', area: 'Patio', category: 'General' },
  ],
  '2-2': [ // 2 Bed 2 Bath
    // Master Bedroom
    { label: 'Ceiling fan', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Outlets', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Wall switch plate', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Closet globe', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Blinds', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Window screen', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Entry door', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Door stop', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Master Bedroom', category: 'HVAC/Ventilation' },
    { label: 'Paint', area: 'Master Bedroom', category: 'Paint/Finishes' },
    { label: 'Carpet', area: 'Master Bedroom', category: 'Flooring' },
    // Master Bathroom
    { label: 'Light bulbs', area: 'Master Bathroom', category: 'Electrical' },
    { label: 'Switch cover', area: 'Master Bathroom', category: 'Electrical' },
    { label: 'Exhaust fan', area: 'Master Bathroom', category: 'Electrical' },
    { label: 'Toilet', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Toilet seat', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Sink', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Shower head', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Tub', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Tub drain', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Diverter', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Faucet', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Cabinets', area: 'Master Bathroom', category: 'Cabinetry' },
    { label: 'TP roll holder', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Towel bar', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Shower rod', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door stop', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door', area: 'Master Bathroom', category: 'Doors & Windows' },
    { label: 'Closet door', area: 'Master Bathroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Master Bathroom', category: 'HVAC/Ventilation' },
    { label: 'Countertops', area: 'Master Bathroom', category: 'Paint/Finishes' },
    { label: 'Tub surround', area: 'Master Bathroom', category: 'Paint/Finishes' },
    { label: 'Closet shelves', area: 'Master Bathroom', category: 'Paint/Finishes' },
    // Spare Bedroom
    { label: 'Ceiling fan', area: 'Spare Bedroom', category: 'Electrical' },
    { label: 'Outlets', area: 'Spare Bedroom', category: 'Electrical' },
    { label: 'Wall switch plate', area: 'Spare Bedroom', category: 'Electrical' },
    { label: 'Closet globe', area: 'Spare Bedroom', category: 'Electrical' },
    { label: 'Blinds', area: 'Spare Bedroom', category: 'Doors & Windows' },
    { label: 'Window screen', area: 'Spare Bedroom', category: 'Doors & Windows' },
    { label: 'Door', area: 'Spare Bedroom', category: 'Doors & Windows' },
    { label: 'Door stop', area: 'Spare Bedroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Spare Bedroom', category: 'HVAC/Ventilation' },
    { label: 'Paint', area: 'Spare Bedroom', category: 'Paint/Finishes' },
    { label: 'Carpet', area: 'Spare Bedroom', category: 'Flooring' },
    // Guest Bathroom
    { label: 'Light bulbs', area: 'Guest Bathroom', category: 'Electrical' },
    { label: 'Switch cover', area: 'Guest Bathroom', category: 'Electrical' },
    { label: 'Exhaust fan', area: 'Guest Bathroom', category: 'Electrical' },
    { label: 'Toilet', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Toilet seat', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Sink', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Shower head', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Tub', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Tub drain', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Diverter', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Faucet', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Cabinets', area: 'Guest Bathroom', category: 'Cabinetry' },
    { label: 'TP roll holder', area: 'Guest Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Towel bar', area: 'Guest Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Shower rod', area: 'Guest Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door stop', area: 'Guest Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door', area: 'Guest Bathroom', category: 'Doors & Windows' },
    { label: 'Closet door', area: 'Guest Bathroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Guest Bathroom', category: 'HVAC/Ventilation' },
    { label: 'Countertops', area: 'Guest Bathroom', category: 'Paint/Finishes' },
    { label: 'Tub surround', area: 'Guest Bathroom', category: 'Paint/Finishes' },
    { label: 'Closet shelves', area: 'Guest Bathroom', category: 'Paint/Finishes' },
    // Kitchen
    { label: 'Range', area: 'Kitchen', category: 'Appliances' },
    { label: 'Refrigerator', area: 'Kitchen', category: 'Appliances' },
    { label: 'Dishwasher', area: 'Kitchen', category: 'Appliances' },
    { label: 'Sink', area: 'Kitchen', category: 'Plumbing' },
    { label: 'Faucet', area: 'Kitchen', category: 'Plumbing' },
    { label: 'Cabinet doors', area: 'Kitchen', category: 'Cabinetry' },
    { label: 'Countertops', area: 'Kitchen', category: 'Paint/Finishes' },
    { label: 'Paint', area: 'Kitchen', category: 'Paint/Finishes' },
    { label: 'Tile backsplash', area: 'Kitchen', category: 'Paint/Finishes' },
    { label: 'Light fixtures', area: 'Kitchen', category: 'Electrical' },
    { label: 'Outlets', area: 'Kitchen', category: 'Electrical' },
    { label: 'Register', area: 'Kitchen', category: 'HVAC/Ventilation' },
    // Living/Dining
    { label: 'Ceiling fan', area: 'Living/Dining Room', category: 'Electrical' },
    { label: 'Light fixtures', area: 'Living/Dining Room', category: 'Electrical' },
    { label: 'Outlets', area: 'Living/Dining Room', category: 'Electrical' },
    { label: 'Window blinds', area: 'Living/Dining Room', category: 'Doors & Windows' },
    { label: 'Window screens', area: 'Living/Dining Room', category: 'Doors & Windows' },
    { label: 'Sliding glass door', area: 'Living/Dining Room', category: 'Doors & Windows' },
    { label: 'Paint', area: 'Living/Dining Room', category: 'Paint/Finishes' },
    { label: 'Flooring', area: 'Living/Dining Room', category: 'Flooring' },
    { label: 'Register', area: 'Living/Dining Room', category: 'HVAC/Ventilation' },
    // Entry/Hallway
    { label: 'Light fixture', area: 'Entry/Hallway', category: 'Electrical' },
    { label: 'Outlets', area: 'Entry/Hallway', category: 'Electrical' },
    { label: 'Entry door', area: 'Entry/Hallway', category: 'Doors & Windows' },
    { label: 'Door frame', area: 'Entry/Hallway', category: 'Doors & Windows' },
    { label: 'Paint', area: 'Entry/Hallway', category: 'Paint/Finishes' },
    { label: 'Flooring', area: 'Entry/Hallway', category: 'Flooring' },
    // Laundry
    { label: 'Washer/Dryer hookup', area: 'Laundry', category: 'Plumbing' },
    { label: 'Vent to exterior', area: 'Laundry', category: 'HVAC/Ventilation' },
    // A/C Closet
    { label: 'Filter', area: 'A/C Closet', category: 'HVAC/Ventilation' },
    { label: 'Heat', area: 'A/C Closet', category: 'HVAC/Ventilation' },
    { label: 'A/C', area: 'A/C Closet', category: 'HVAC/Ventilation' },
    { label: 'Water heater', area: 'A/C Closet', category: 'Plumbing' },
    { label: 'Condensate lines', area: 'A/C Closet', category: 'Plumbing' },
    { label: 'Drip pan', area: 'A/C Closet', category: 'Plumbing' },
    // Patio
    { label: 'Globe', area: 'Patio', category: 'Electrical' },
    { label: 'Closet door', area: 'Patio', category: 'Doors & Storage' },
    { label: 'Decking', area: 'Patio', category: 'General' },
  ],
  '3-2': [ // 3 Bed 2 Bath
    // Master Bedroom
    { label: 'Ceiling fan', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Outlets', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Wall switch plate', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Closet globe', area: 'Master Bedroom', category: 'Electrical' },
    { label: 'Blinds', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Window screen', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Entry door', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Door stop', area: 'Master Bedroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Master Bedroom', category: 'HVAC/Ventilation' },
    { label: 'Paint', area: 'Master Bedroom', category: 'Paint/Finishes' },
    { label: 'Carpet', area: 'Master Bedroom', category: 'Flooring' },
    // Master Bathroom
    { label: 'Light bulbs', area: 'Master Bathroom', category: 'Electrical' },
    { label: 'Switch cover', area: 'Master Bathroom', category: 'Electrical' },
    { label: 'Exhaust fan', area: 'Master Bathroom', category: 'Electrical' },
    { label: 'Toilet', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Toilet seat', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Sink', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Shower head', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Tub', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Tub drain', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Diverter', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Faucet', area: 'Master Bathroom', category: 'Plumbing' },
    { label: 'Cabinets', area: 'Master Bathroom', category: 'Cabinetry' },
    { label: 'TP roll holder', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Towel bar', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Shower rod', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door stop', area: 'Master Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door', area: 'Master Bathroom', category: 'Doors & Windows' },
    { label: 'Closet door', area: 'Master Bathroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Master Bathroom', category: 'HVAC/Ventilation' },
    { label: 'Countertops', area: 'Master Bathroom', category: 'Paint/Finishes' },
    { label: 'Tub surround', area: 'Master Bathroom', category: 'Paint/Finishes' },
    { label: 'Closet shelves', area: 'Master Bathroom', category: 'Paint/Finishes' },
    // Spare Bedroom
    { label: 'Ceiling fan', area: 'Spare Bedroom', category: 'Electrical' },
    { label: 'Outlets', area: 'Spare Bedroom', category: 'Electrical' },
    { label: 'Wall switch plate', area: 'Spare Bedroom', category: 'Electrical' },
    { label: 'Closet globe', area: 'Spare Bedroom', category: 'Electrical' },
    { label: 'Blinds', area: 'Spare Bedroom', category: 'Doors & Windows' },
    { label: 'Window screen', area: 'Spare Bedroom', category: 'Doors & Windows' },
    { label: 'Door', area: 'Spare Bedroom', category: 'Doors & Windows' },
    { label: 'Door stop', area: 'Spare Bedroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Spare Bedroom', category: 'HVAC/Ventilation' },
    { label: 'Paint', area: 'Spare Bedroom', category: 'Paint/Finishes' },
    { label: 'Carpet', area: 'Spare Bedroom', category: 'Flooring' },
    // Guest Bedroom
    { label: 'Ceiling fan', area: 'Guest Bedroom', category: 'Electrical' },
    { label: 'Outlets', area: 'Guest Bedroom', category: 'Electrical' },
    { label: 'Wall switch plate', area: 'Guest Bedroom', category: 'Electrical' },
    { label: 'Closet globe', area: 'Guest Bedroom', category: 'Electrical' },
    { label: 'Blinds', area: 'Guest Bedroom', category: 'Doors & Windows' },
    { label: 'Window screen', area: 'Guest Bedroom', category: 'Doors & Windows' },
    { label: 'Door', area: 'Guest Bedroom', category: 'Doors & Windows' },
    { label: 'Door stop', area: 'Guest Bedroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Guest Bedroom', category: 'HVAC/Ventilation' },
    { label: 'Paint', area: 'Guest Bedroom', category: 'Paint/Finishes' },
    { label: 'Carpet', area: 'Guest Bedroom', category: 'Flooring' },
    // Guest Bathroom
    { label: 'Light bulbs', area: 'Guest Bathroom', category: 'Electrical' },
    { label: 'Switch cover', area: 'Guest Bathroom', category: 'Electrical' },
    { label: 'Exhaust fan', area: 'Guest Bathroom', category: 'Electrical' },
    { label: 'Toilet', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Toilet seat', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Sink', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Shower head', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Tub', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Tub drain', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Diverter', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Faucet', area: 'Guest Bathroom', category: 'Plumbing' },
    { label: 'Cabinets', area: 'Guest Bathroom', category: 'Cabinetry' },
    { label: 'TP roll holder', area: 'Guest Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Towel bar', area: 'Guest Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Shower rod', area: 'Guest Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door stop', area: 'Guest Bathroom', category: 'Fixtures & Hardware' },
    { label: 'Door', area: 'Guest Bathroom', category: 'Doors & Windows' },
    { label: 'Closet door', area: 'Guest Bathroom', category: 'Doors & Windows' },
    { label: 'Register', area: 'Guest Bathroom', category: 'HVAC/Ventilation' },
    { label: 'Countertops', area: 'Guest Bathroom', category: 'Paint/Finishes' },
    { label: 'Tub surround', area: 'Guest Bathroom', category: 'Paint/Finishes' },
    { label: 'Closet shelves', area: 'Guest Bathroom', category: 'Paint/Finishes' },
    // Kitchen
    { label: 'Range', area: 'Kitchen', category: 'Appliances' },
    { label: 'Refrigerator', area: 'Kitchen', category: 'Appliances' },
    { label: 'Dishwasher', area: 'Kitchen', category: 'Appliances' },
    { label: 'Sink', area: 'Kitchen', category: 'Plumbing' },
    { label: 'Faucet', area: 'Kitchen', category: 'Plumbing' },
    { label: 'Cabinet doors', area: 'Kitchen', category: 'Cabinetry' },
    { label: 'Countertops', area: 'Kitchen', category: 'Paint/Finishes' },
    { label: 'Paint', area: 'Kitchen', category: 'Paint/Finishes' },
    { label: 'Tile backsplash', area: 'Kitchen', category: 'Paint/Finishes' },
    { label: 'Light fixtures', area: 'Kitchen', category: 'Electrical' },
    { label: 'Outlets', area: 'Kitchen', category: 'Electrical' },
    { label: 'Register', area: 'Kitchen', category: 'HVAC/Ventilation' },
    // Living/Dining
    { label: 'Ceiling fan', area: 'Living/Dining Room', category: 'Electrical' },
    { label: 'Light fixtures', area: 'Living/Dining Room', category: 'Electrical' },
    { label: 'Outlets', area: 'Living/Dining Room', category: 'Electrical' },
    { label: 'Window blinds', area: 'Living/Dining Room', category: 'Doors & Windows' },
    { label: 'Window screens', area: 'Living/Dining Room', category: 'Doors & Windows' },
    { label: 'Sliding glass door', area: 'Living/Dining Room', category: 'Doors & Windows' },
    { label: 'Paint', area: 'Living/Dining Room', category: 'Paint/Finishes' },
    { label: 'Flooring', area: 'Living/Dining Room', category: 'Flooring' },
    { label: 'Register', area: 'Living/Dining Room', category: 'HVAC/Ventilation' },
    // Entry/Hallway
    { label: 'Light fixture', area: 'Entry/Hallway', category: 'Electrical' },
    { label: 'Outlets', area: 'Entry/Hallway', category: 'Electrical' },
    { label: 'Entry door', area: 'Entry/Hallway', category: 'Doors & Windows' },
    { label: 'Door frame', area: 'Entry/Hallway', category: 'Doors & Windows' },
    { label: 'Paint', area: 'Entry/Hallway', category: 'Paint/Finishes' },
    { label: 'Flooring', area: 'Entry/Hallway', category: 'Flooring' },
    // Laundry
    { label: 'Washer/Dryer hookup', area: 'Laundry', category: 'Plumbing' },
    { label: 'Vent to exterior', area: 'Laundry', category: 'HVAC/Ventilation' },
    // A/C Closet
    { label: 'Filter', area: 'A/C Closet', category: 'HVAC/Ventilation' },
    { label: 'Heat', area: 'A/C Closet', category: 'HVAC/Ventilation' },
    { label: 'A/C', area: 'A/C Closet', category: 'HVAC/Ventilation' },
    { label: 'Water heater', area: 'A/C Closet', category: 'Plumbing' },
    { label: 'Condensate lines', area: 'A/C Closet', category: 'Plumbing' },
    { label: 'Drip pan', area: 'A/C Closet', category: 'Plumbing' },
    // Patio
    { label: 'Globe', area: 'Patio', category: 'Electrical' },
    { label: 'Closet door', area: 'Patio', category: 'Doors & Storage' },
    { label: 'Decking', area: 'Patio', category: 'General' },
  ],
};

/**
 * Get punch list items for a given bed/bath configuration
 * @param beds Number of bedrooms
 * @param baths Number of bathrooms
 * @returns Array of punch list items or default to 2-2
 */
export function getPunchListItems(beds?: number, baths?: number): PunchListItemData[] {
  if (!beds || !baths) {
    return punchListTemplates['2-2']; // Default to 2 bed 2 bath
  }

  const key = `${beds}-${baths}`;
  return punchListTemplates[key] || punchListTemplates['2-2'];
}
